name: PomaExpansion
author: poma123
main: me.poma123.pomaexpansion.PomaExpansion
website: https://github.com/TheOld-Crafters/PomaExpansion
depend: [Slimefun]
loadbefore: [PlotSquared]
version: 1.3.1
api-version: 1.16
