name: PomaExpansion
author: poma123
main: me.poma123.pomaexpansion.PomaExpansion
website: https://github.com/TheOld-Crafters/PomaExpansion
depend: [Slimefun]
softdepend: [LiteXpansion]
loadbefore: [PlotSquared]
version: UNOFFICIAL
api-version: 1.14
